apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: sulabh-aap
  namespace: sulabh-aap
spec:
  logLevel: info
  startDelay: 3600
  stopDelay: 1800
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  smartShutdownTimeout: 180
  backup:
    target: prefer-standby
    volumeSnapshot:
      online: true
      onlineConfiguration:
        immediateCheckpoint: false
        waitForArchive: true
      snapshotOwnerReference: none
  probes:
    liveness:
      isolationCheck:
        connectionTimeout: 1000
        enabled: true
        requestTimeout: 1000
  externalClusters:
    - connectionParameters:
        dbname: postgres
        host: '10.0.54.5,10.0.54.6,10.0.54.7'
        port: '30432'
        sslmode: require
        user: streaming_replica
      name: sulabh-aap
      password:
        key: password
        name: primary-superuser-secret
      sslCert:
        key: tls.crt
        name: sulabh-prod-replication
      sslKey:
        key: tls.key
        name: sulabh-prod-replication
      sslRootCert:
        key: ca.crt
        name: sulabh-prod-ca
  resources: {}
  imageName: 'quay.io/enterprisedb/postgresql:17.6'
  enableSuperuserAccess: false
  monitoring:
    customQueriesConfigMap:
      - key: queries
        name: postgresql-operator-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: false
    tls:
      enabled: false
  affinity:
    podAntiAffinityType: preferred
  minSyncReplicas: 0
  postgresGID: 26
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnp_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  enablePDB: true
  primaryUpdateMethod: restart
  bootstrap:
    pg_basebackup:
      database: app
      owner: app
      source: sulabh-aap
  failoverDelay: 0
  postgresql:
    parameters:
      log_truncate_on_rotation: 'false'
      archive_mode: always
      log_filename: postgres
      archive_timeout: 5min
      max_replication_slots: '32'
      log_rotation_size: '0'
      wal_level: logical
      shared_preload_libraries: ''
      logging_collector: 'on'
      wal_receiver_timeout: 5s
      ssl_min_protocol_version: TLSv1.3
      log_directory: /controller/log
      log_destination: csvlog
      wal_sender_timeout: 5s
      wal_log_hints: 'on'
      full_page_writes: 'on'
      max_worker_processes: '32'
      max_parallel_workers: '32'
      log_rotation_age: '0'
      shared_memory_type: mmap
      dynamic_shared_memory_type: posix
      wal_keep_size: 512MB
      ssl_max_protocol_version: TLSv1.3
    syncReplicaElectionConstraint:
      enabled: false
  postgresUID: 26
  replica:
    enabled: true
    source: sulabh-aap
  walStorage:
    pvcTemplate:
      resources: {}
      storageClassName: foobar
      volumeName: pv-wal
    resizeInUseVolumes: true
    size: 1Gi
  maxSyncReplicas: 0
  switchoverDelay: 3600
  storage:
    pvcTemplate:
      resources: {}
      storageClassName: foobar
      volumeName: pv-data
    resizeInUseVolumes: true
    size: 1Gi
    storageClass: foobar
  primaryUpdateStrategy: unsupervised
  instances: 1

