kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-data
spec:
  capacity:
    storage: 50Gi
  local:
    path: /mnt/disks/data
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: foobar
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage
              operator: In
              values:
                - enabled

