kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-wal
spec:
  capacity:
    storage: 30Gi
  local:
    path: /mnt/disks/wal
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: foobar
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage
              operator: In
              values:
                - enabled

