apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aap-hub-file-storage
  namespace: sulabh-postgres
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
